server:
  port: 8080  # ?? ?? ??

spring:
  datasource:
    url: jdbc:h2:mem:testdb  # H2 ??? DB
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true  # H2 ? ?? ??? (localhost:8080/h2-console)
  data:
    redis:
      host: localhost
      port: 6379  # Redis ?? ??jackson:

    serialization:
      fail-on-empty-beans: false  # JSON ??? ?? ??
